# Generated by Django 6.0.3 on 2026-03-12 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('current_location', models.CharField(max_length=200)),
                ('preferred_job_location', models.CharField(max_length=200)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('career_objective', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('job_seeker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredJobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('job_seeker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('job_seeker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekerprofile')),
            ],
        ),
    ]
