# Generated by Django 6.0.3 on 2026-03-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(to='skill.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory'),
        ),
    ]
